//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.14 at 11:05:11 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.intellect.com/spring/soap/api/loanEligibility", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.intellect.spring.soap.api.loaneligibility;
